function [Q,r2_OW,state_OW,sigma_w2,vort2] = fct_okubo_weiss(grid,w,ax)
% Compute and plot the expected stretching based on the Okubo-Weiss
% assumptions.
% This function can also plot the Okubo-Weiss criterion and
% the ratio r of rotation and strain (when additional_plots = true).
%

if nargin < 4
    day ='0';
end
loc_colorbar = 'southoutside';
colormap_ = 'default';

%% Velocity gradient

% Velocity gradient
grad_w = gradient_mat_2(permute( w,[ 1 2 4 3]),grid.dX);
% Mx My 2(grad) 2(w 2D) N_t

% Strain
sigma_s = grad_w(:,:,1,2,:) + grad_w(:,:,2,1,:);
sigma_n = grad_w(:,:,1,1,:) - grad_w(:,:,2,2,:);
vector_sigma_w = sigma_s + 1i * sigma_n;
vector_sigma_w = permute(vector_sigma_w, [ 1 2 3 5 4]); % Mx My 1 N_t
clear sigma_s sigma_n

sigma_w = abs(vector_sigma_w);
sigma_w2 = sigma_w.^2;

% Rotation (vorticity)
vort = grad_w(:,:,1,2,:) - grad_w(:,:,2,1,:);
vort = permute(vort, [ 1 2 3 5 4]);
vort2 = vort.^2;

%% Criterion Q
Q = 1/4 * ( sigma_w2 - vort2);

%% Criterion Okubo-Weiss
% ratio of rotation and strain
r_OW = (vort)./sigma_w;

%% Plots

% Grid
x = grid.x_ref;
y = grid.y_ref;

r2_OW=r_OW.^2;


taille_police = 12;
% width=8;
% height=12;
width=4;
height=10;
X0=[0 0];

% figure(48);
% close;
figure48=figure(48);
set(figure48,'Units','inches', ...
    'Position',[X0(1) X0(2) width height], ...
    'PaperPositionMode','auto');

subplot(5,1,1)
imagesc(x,y,Q');
colorbar;axis xy;axis equal
if nargin > 2
    axis(ax);
end
set(gca,...
    'Units','normalized',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')

ylabel('x',...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',taille_police,...
    'FontName','Times')
xlabel('y',...
    'interpreter','latex',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')

title('Q-criterion',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'interpreter','latex',...
    'FontSize',12,...
    'FontName','Times')
%colormap('winter')

colormap(colormap_)


subplot(5,1,2)
imagesc(x,y,(1./r2_OW(:,:,:))');
colorbar;axis xy;axis equal
if nargin > 2
    axis(ax);
end
set(gca,...
    'Units','normalized',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')

ylabel('x',...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',taille_police,...
    'FontName','Times')
xlabel('y',...
    'interpreter','latex',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')

title('OW 1/r2',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'interpreter','latex',...
    'FontSize',12,...
    'FontName','Times')
caxis([0 10]);
%colormap('winter')

colormap(colormap_)



%colorbar('location',loc_colorbar)

% state_OW = 2 : hyperbolic
% state_OW = 1 : intermediate (stretching linear in time)
% state_OW = 0 : elliptic
tol = 1e-1;
state_OW = 2 * (r2_OW < (1 - tol)) ...
    + 1 * ( ((1-tol) <= r2_OW) & (r2_OW <= (1 + tol)) ) ...
    + 0 * (r2_OW > (1 +tol));

%figure(42);
% close;
% figure42=figure(42);
% set(figure42,'Units','inches', ...
%     'Position',[X0(1) X0(2) width height], ...
%     'PaperPositionMode','auto');

subplot(5,1,3)
imagesc(x,y,(state_OW(:,:,:))');
colorbar;axis xy;axis equal
caxis([0 2]);
if nargin > 2
    axis(ax);
end
set(gca,...
    'Units','normalized',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')
ylabel('x',...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',taille_police,...
    'FontName','Times')
xlabel('y',...
    'interpreter','latex',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')
title('OW states',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'interpreter','latex',...
    'FontSize',12,...
    'FontName','Times')
%colormap('winter')

colormap(colormap_)
%colorbar('location',loc_colorbar)

%drawnow
%     eval( ['print -depsc ' model.folder.folder_simu '/' ...
%         'OW_state.eps']);


%% Plots

% Grid
x = grid.x_ref;
y = grid.y_ref;

r2_OW=r_OW.^2;


taille_police = 12;
width=4;
height=6;
X0=[0 3];

% % figure(48);
% % close;
% figure4=figure(4);
% set(figure4,'Units','inches', ...
%     'Position',[X0(1) X0(2) width height], ...
%     'PaperPositionMode','auto');

subplot(5,1,4)
imagesc(x,y,sqrt(sigma_w2)');
colorbar;axis xy;axis equal
if nargin > 2
    axis(ax);
end
set(gca,...
    'Units','normalized',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')

ylabel('x',...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',taille_police,...
    'FontName','Times')
xlabel('y',...
    'interpreter','latex',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')

title('$\sigma$',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'interpreter','latex',...
    'FontSize',12,...
    'FontName','Times')
%colormap('winter')

colormap(colormap_)


subplot(5,1,5)
imagesc(x,y,vort');
colorbar;axis xy;axis equal
if nargin > 2
    axis(ax);
end
set(gca,...
    'Units','normalized',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')

ylabel('x',...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',taille_police,...
    'FontName','Times')
xlabel('y',...
    'interpreter','latex',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')

title('$\omega$',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'interpreter','latex',...
    'FontSize',12,...
    'FontName','Times')
% caxis([0 10]);
%colormap('winter')

colormap(colormap_)




%drawnow
%     eval( ['print -depsc ' model.folder.folder_simu '/' ...
%         'OW_state.eps']);



