function FTLE = fct_FTLE(grid,nabla_phi,time_t,ax)
% This function plots carcterisation of stretching (alpha^2, beta/alpha,
% mesochronic vorticity, FTLEs)
%

% day = num2str(floor(t*model.advection.dt_adv/(3600*24)));
loc_colorbar = 'southoutside';
colormap_ = 'default';
% colormap_ = 'jet';
taille_police = 12;

% Grid
x = grid.x_ref;
y = grid.y_ref;

%% Caracterisation of the stretching

% alpha^2
alpha2 = 1/2*sum(sum(nabla_phi.^2,4),3)-1;
alpha2 = alpha2 .* (alpha2 >eps );

% Beta/alpha
beta_alpha = sqrt((alpha2+2)./alpha2);
s=size(beta_alpha);
id_beta = isinf(beta_alpha(:));
beta_alpha(id_beta)=0;
beta_alpha=reshape(beta_alpha,s);

%% FTLE

FTLE = 1 + alpha2 .* ( 1 + beta_alpha );
FTLE = 1/(2*time_t) * log(FTLE);

width=6;
% width=12;
height=4;
% width=12;
% height=8;


% figure6=figure(6);
% close(figure6);
figure6=figure(6);
set(figure6,'Units','inches', ...
    'Position',[15 20 width 2*height], ...
    'PaperPositionMode','auto');
%     'Position',[5 20 width 2*height], ...
%     'PaperPositionMode','auto');
subplot(2,1,1)

imagesc(x,y,FTLE');
% imagesc(x(2:end-1),y(2:end-1),(alpha2((2:end-1),2:My-3))'/time_t^2);
axis equal
axis xy
if nargin > 3
    axis(ax);
else
    axis([x(1) x(end) y(1) y(end)])
end
colormap(colormap_)
colorbar('location',loc_colorbar)
%         in mesohyperbolic areas
% title('$\alpha^2$',...
title('FTLE',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'interpreter','latex',...
    'FontSize',12,...
    'FontName','Times');
set(gca,...
    'Units','normalized',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',11,...
    'FontName','Times')
ylabel('x',...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',taille_police,...
    'FontName','Times')
xlabel('y',...
    'interpreter','latex',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')

%drawnow
% eval( ['print -depsc ' model.folder.folder_simu ...
%     '/mezic_mixing_lonlat/FTLE_' num2str(day) '.eps']);

%% Only alpha


width=9;
% width=12;
height=4;
% figure5=figure(5);
% close(figure5);
% figure5=figure(5);
% set(figure5,'Units','inches', ...
%     'Position',[10 20 width 2*height], ...
%     'PaperPositionMode','auto');
subplot(2,1,2)

imagesc(x,y,alpha2'/time_t^2);
% imagesc(x(2:end-1),y(2:end-1),(alpha2((2:end-1),2:My-3))'/time_t^2);
axis equal
axis xy
if nargin > 3
    axis(ax);
else
    axis([x(1) x(end) y(1) y(end)])
end
colormap(colormap_)
colorbar('location',loc_colorbar)
%         in mesohyperbolic areas
% title('$\alpha^2$',...
title('$\alpha^2 / t^2$',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'interpreter','latex',...
    'FontSize',12,...
    'FontName','Times');
set(gca,...
    'Units','normalized',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',11,...
    'FontName','Times')
ylabel('x',...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',taille_police,...
    'FontName','Times')
xlabel('y',...
    'interpreter','latex',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')
cax = caxis;
axis([x(1) x(end) y(1) y(end)])

%drawnow
% eval( ['print -depsc ' model.folder.folder_simu ...
%     '/mixing/FTLE_' ...
%     num2str(day) '.eps']);

