function plot_wave(model,wave,time,grid,...
    nb_fig,title_,name_save)

% ratio_plot_by_day = 100;

H_max = 4;
% H_max = 3;

if nargin < 4
    grid = model.grid;
end

if nargin < 5
    nb_fig = 10;
end

if nargin < 6
    title_ = 'Wave';
end

if nargin < 7
    name_save = 'wave';
end

taille_police = 12;
X0 = [3 0];
width = 4;
height = 3;

figure12=figure(12);
subplot(3,1,nb_fig)
% figure10=figure(nb_fig);
widthtemp = 10;

set(12,'Units','inches', ...
    'Position',[X0(1) X0(2) width 3*height], ...
    'PaperPositionMode','auto');
% heighttemp = 5;
% set(figure10,'Units','inches', ...
%     'Position',[X0 widthtemp heighttemp], ...
%     'PaperPositionMode','auto');
% subplot(1,2,1)
% surf(grid.Y,grid.X,wave(:,end:-1:1)')
% % axis equal;
% subplot(1,2,2)

heighttemp = 10;

cla
s = surface(model.grid.X,model.grid.Y,wave(end:-1:1,end:-1:1));
s.EdgeColor = 'none';
axis xy
view(3);colorbar;
ax=axis; ax(5:6) = H_max*[-1 1];axis(ax);
caxis(ax(5:6));

% imagesc(grid.x,grid.y,wave')
% axis xy;axis equal;colorbar

% caxis([-2 2])
set(gca,...
    'Units','normalized',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')
ylabel('$y(m)$',...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',taille_police,...
    'FontName','Times')
xlabel('$x(m)$',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'interpreter','latex',...
    'FontName','Times')
% % title(['Wave at time ' num2str(time) ],...
% title([title_ ' at time ' num2str(time) ],...
%     'FontUnits','points',...
%     'FontWeight','normal',...
%     'interpreter','latex',...
%     'FontSize',12,...
%     'FontName','Times')

% % title(['Wave at time ' num2str(time) ],...
% idx_day = (floor(time/24/3600*ratio_plot_by_day))/ratio_plot_by_day;
% time = time - idx_day*3600*24;
% % idx_day = (floor(time/24/3600));
% % idx_0_1day = (floor(ratio_plot_by_day*(time/24/3600 - idx_day)));
% % time = time - (idx_day+idx_0_1day/ratio_plot_by_day)*3600*24;
time = time - eval(title_)*3600*24;
% title([num2str(idx_day) 'days + ' ...
%     num2str(time) 'sec'],...
%     'FontUnits','points',...
%     'FontWeight','normal',...
%     'interpreter','latex',...
%     'FontSize',12,...
%     'FontName','Times')
title([title_ 'days + ' ...
    num2str(time) 'sec'],...
    'FontUnits','points',...
    'FontWeight','normal',...
    'interpreter','latex',...
    'FontSize',12,...
    'FontName','Times')

%% Save plot
% drawnow
% folder_simu = model.folder.folder_simu;

% eval( ['print -dpng ' folder_simu '/' name_save '_' num2str(time) '.png']);
% % eval( ['print -depsc ' folder_simu '/' name_save '_' num2str(time) '.eps']);
% % eval( ['print -depsc ' folder_simu '/wave_' num2str(time) '.eps']);




%% Spectrum
X0=[6 0];
% X0=[10 7];
% nb_fig_sp = 10 + nb_fig;
% close(figure(nb_fig_sp))
% figure4=figure(nb_fig_sp);
figure4=figure(4);
subplot(3,1,nb_fig)

widthtemp = 12;
heighttemp = 6;
set(figure4,'Units','inches', ...
    'Position',[X0(1) X0(2) widthtemp 3*heighttemp], ...
    'PaperPositionMode','auto');
fct_spectrum_wave( grid,fft2(wave),'b');
% [spectrum,name_plot,int_epsilon] = fct_spectrum( model,fft2(wave),'b');
set(gca,'XGrid','on','XTickMode','manual');
width = 4;
height = 3;
set(figure4,'Units','inches', ...
    'Position',[X0(1) X0(2) width 3*height], ...
    'PaperPositionMode','auto');
set(gca,'YGrid','on')

set(gca,...
    'Units','normalized',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')
% ylabel('$|\hat{b}(\kappa)|^2$',...
% ylabel('$S_h(\kappa) \bigl ( m^{3}.s^{-4}.{rad}^{-1} \bigr )$',...
%     'FontUnits','points',...
%     'interpreter','latex',...
%     'FontSize',taille_police,...
%     'FontName','Times')
xlabel('$\kappa \bigl ( rad.m^{-1} \bigr )$',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'interpreter','latex',...
    'FontName','Times')
% % title({'Spectrum of' ...
% %     '\hspace{0.5cm} one realization'},...
% title([title_ ' spectrum at time ' num2str(time) ],...
%     'FontUnits','points',...
%     'FontWeight','normal',...
%     'interpreter','latex',...
%     'FontSize',12,...
%     'FontName','Times')
% drawnow

% eval( ['print -dpng ' folder_simu '/Spectrum_' name_save '_' num2str(time) '.png']);
